#!/bin/sh
set -eu

if [ -n "${AGENT_REMOTE_HOME:-}" ]; then
  agent_remote_home=$AGENT_REMOTE_HOME
else
  : "${HOME:?HOME is not set}"
  agent_remote_home=$HOME/.config/agent-remote
fi
ssh_dir=$agent_remote_home/ssh
known_hosts=$ssh_dir/known_hosts
mkdir -p "$ssh_dir"
chmod 700 "$ssh_dir"
touch "$known_hosts"
chmod 600 "$known_hosts"

exec /usr/bin/ssh \
  -o StrictHostKeyChecking=accept-new \
  -o "UserKnownHostsFile=$known_hosts" \
  "$@"
